/**
 * face-align.js — the geometry half of browser-side face recognition.
 *
 * SFace does not embed a raw crop: it embeds a face that has been ALIGNED onto a fixed 112x112
 * canonical pose using the five landmarks YuNet returns (eyes, nose, mouth corners). Alignment is
 * what makes recognition robust to head turn and camera distance, and it is not optional — feeding
 * SFace an unaligned crop produces a vector in a different part of the space, so matching quietly
 * degrades instead of failing loudly.
 *
 * On the edge agent OpenCV does this via FaceRecognizerSF::alignCrop. The browser has no OpenCV, so
 * this module re-implements it. Getting it *nearly* right is the dangerous outcome, so the port is
 * pinned by fixtures generated from OpenCV itself (test/fixtures/align-fixture.json, regenerated by
 * src/scripts/gen_align_fixture.py). Measured agreement on a real detection: aligned crops differ
 * by at most 1/255 per pixel and the resulting embeddings have cosine 0.99999983 — far inside the
 * 0.363 recognition threshold, so a face enrolled in the browser and one enrolled by a Pi camera
 * are interchangeable.
 *
 * Pure functions only (no DOM, no ORT) so this is testable under `node --test`.
 */

/** SFace's reference landmark positions in the 112x112 aligned crop (the ArcFace canonical five). */
export const REFERENCE_POINTS = [
  [38.2946, 51.6963],   // right eye
  [73.5318, 51.5014],   // left eye
  [56.0252, 71.7366],   // nose tip
  [41.5493, 92.3655],   // right mouth corner
  [70.7299, 92.2041],   // left mouth corner
];

export const ALIGNED_SIZE = 112;

/**
 * Least-squares similarity transform (uniform scale + rotation + translation) mapping `src` onto
 * `dst` — the Umeyama (1991) solution.
 *
 * OpenCV's alignCrop calls estimateAffinePartial2D, which fits the same 4-DOF family. With exactly
 * five corresponding points and no outliers its robust estimator lands on the least-squares answer,
 * which is why this closed form reproduces it (see the fixtures). A full 6-DOF affine fit would NOT
 * be equivalent — it can shear the face, which SFace was never trained on.
 *
 * @param {number[][]} src 5 source points [[x,y],…]
 * @param {number[][]} dst 5 destination points
 * @returns {number[]} [a, b, tx, c, d, ty] — a 2x3 matrix in row-major order
 */
export function similarityTransform(src, dst) {
  const n = src.length;
  let msx = 0, msy = 0, mdx = 0, mdy = 0;
  for (let i = 0; i < n; i++) { msx += src[i][0]; msy += src[i][1]; mdx += dst[i][0]; mdy += dst[i][1]; }
  msx /= n; msy /= n; mdx /= n; mdy /= n;

  // Covariance of the centred point sets, plus the source variance used to recover scale.
  let c00 = 0, c01 = 0, c10 = 0, c11 = 0, srcVar = 0;
  for (let i = 0; i < n; i++) {
    const sx = src[i][0] - msx, sy = src[i][1] - msy;
    const dx = dst[i][0] - mdx, dy = dst[i][1] - mdy;
    c00 += dx * sx; c01 += dx * sy;
    c10 += dy * sx; c11 += dy * sy;
    srcVar += sx * sx + sy * sy;
  }
  c00 /= n; c01 /= n; c10 /= n; c11 /= n; srcVar /= n;

  // For 2x2 the rotation that maximises the correlation has a closed form — no SVD needed. The
  // covariance's antisymmetric part gives the sine term and its trace the cosine term, so the
  // rotation angle is atan2(c10 - c01, c00 + c11).
  const sinNum = c10 - c01;
  const cosNum = c00 + c11;
  const norm = Math.hypot(sinNum, cosNum) || 1;
  const cos = cosNum / norm, sin = sinNum / norm;

  // Scale is the correlation along the fitted rotation over the source variance. srcVar is 0 only
  // for five identical points, which YuNet cannot produce; guard anyway so a degenerate detection
  // yields an identity-ish transform rather than NaNs propagating into the tensor.
  const scale = srcVar > 1e-12 ? norm / srcVar : 1;

  const a = scale * cos, b = -scale * sin;
  const c = scale * sin, d = scale * cos;
  return [a, b, mdx - (a * msx + b * msy), c, d, mdy - (c * msx + d * msy)];
}

/** Invert a 2x3 affine [a,b,tx,c,d,ty]. Used to map DESTINATION pixels back to source coordinates,
 *  which is how warping avoids leaving holes: iterate over the output, sample the input. */
export function invertAffine(m) {
  const [a, b, tx, c, d, ty] = m;
  const det = a * d - b * c;
  if (Math.abs(det) < 1e-12) return null;
  const ia = d / det, ib = -b / det, ic = -c / det, id = a / det;
  return [ia, ib, -(ia * tx + ib * ty), ic, id, -(ic * tx + id * ty)];
}

/**
 * Warp an RGBA image into the aligned 112x112 face crop, bilinearly sampled.
 *
 * Bilinear (not nearest) on purpose: SFace is sensitive to the resampling used at enrolment vs
 * recognition, and OpenCV's warpAffine defaults to bilinear — matching it is part of matching the
 * embedding space.
 *
 * @param {Uint8ClampedArray} rgba source pixels, 4 bytes/px
 * @param {number} width source width
 * @param {number} height source height
 * @param {number[]} matrix 2x3 source→aligned transform
 * @returns {Uint8ClampedArray} ALIGNED_SIZE*ALIGNED_SIZE*4 RGBA
 */
export function warpToAligned(rgba, width, height, matrix) {
  const inv = invertAffine(matrix);
  const size = ALIGNED_SIZE;
  const out = new Uint8ClampedArray(size * size * 4);
  if (!inv) return out;
  const [ia, ib, itx, ic, id, ity] = inv;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      // Pixel centres, matching OpenCV's convention.
      const sx = ia * x + ib * y + itx;
      const sy = ic * x + id * y + ity;
      const o = (y * size + x) * 4;
      if (sx < 0 || sy < 0 || sx > width - 1 || sy > height - 1) {
        out[o] = out[o + 1] = out[o + 2] = 0; out[o + 3] = 255;   // outside → black, like BORDER_CONSTANT
        continue;
      }
      const x0 = Math.floor(sx), y0 = Math.floor(sy);
      const x1 = Math.min(x0 + 1, width - 1), y1 = Math.min(y0 + 1, height - 1);
      const fx = sx - x0, fy = sy - y0;
      const w00 = (1 - fx) * (1 - fy), w10 = fx * (1 - fy);
      const w01 = (1 - fx) * fy, w11 = fx * fy;
      const p00 = (y0 * width + x0) * 4, p10 = (y0 * width + x1) * 4;
      const p01 = (y1 * width + x0) * 4, p11 = (y1 * width + x1) * 4;
      for (let ch = 0; ch < 3; ch++) {
        out[o + ch] = rgba[p00 + ch] * w00 + rgba[p10 + ch] * w10 +
                      rgba[p01 + ch] * w01 + rgba[p11 + ch] * w11;
      }
      out[o + 3] = 255;
    }
  }
  return out;
}

/** Align one detected face straight from source pixels. `landmarks` is YuNet's five [x,y] pairs. */
export function alignFace(rgba, width, height, landmarks) {
  return warpToAligned(rgba, width, height, similarityTransform(landmarks, REFERENCE_POINTS));
}

/**
 * RGBA crop → the NCHW float tensor SFace expects.
 *
 * SFace takes raw 0-255 BGR values with NO mean/scale normalisation — OpenCV's blobFromImage is
 * called with default scalefactor 1.0 and no mean subtraction. Feeding it 0-1 floats (the usual
 * convention, and the tempting default) produces plausible-looking vectors that simply do not match
 * anything, so both the channel ORDER and the value RANGE matter here.
 */
export function alignedToTensor(alignedRgba) {
  const size = ALIGNED_SIZE, area = size * size;
  const data = new Float32Array(3 * area);
  for (let i = 0; i < area; i++) {
    data[i] = alignedRgba[i * 4 + 2];                 // B
    data[area + i] = alignedRgba[i * 4 + 1];          // G
    data[2 * area + i] = alignedRgba[i * 4];          // R
  }
  return data;
}

/** L2-normalise, so a dot product between two embeddings is their cosine similarity — the same
 *  convention the edge agent and the server's stored vectors use. */
export function l2Normalize(vec) {
  let sum = 0;
  for (let i = 0; i < vec.length; i++) sum += vec[i] * vec[i];
  const norm = Math.sqrt(sum) || 1;
  const out = new Array(vec.length);
  for (let i = 0; i < vec.length; i++) out[i] = vec[i] / norm;
  return out;
}

/** Cosine similarity of two L2-normalised vectors. */
export function cosine(a, b) {
  let s = 0;
  for (let i = 0; i < a.length; i++) s += a[i] * b[i];
  return s;
}
